{% set version = "1.2.2" %}

package:
  name: nifty
  version: {{ version }}

source:
  url: https://github.com/DerThorsten/nifty/archive/v{{ version }}.tar.gz
  sha256: 43e6ecfd72076acd08a4049f3fc4698c5e39715caec12f70d47c303c519e1a2d
  patches:
    # Take from 1.2.2 to 
    # https://github.com/DerThorsten/nifty/pull/150
    - 0001-Prevent-debug-builds-in-windows-to-fix-conda-forge-b.patch
    - 0002-Fix-CIs.patch
    - 0003-Update-CMake-file-to-use-FindPython.patch

build:
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - xtensor >=0.25,<0.26
    - xtensor-python >=0.27,<0.28
    - libboost-devel
    - libvigra
    # Vigra Numpy is used at link time too
    - vigra
    - z5py >=2.0.11
    # build dependencies needed for z5
    - nlohmann_json
    - blosc
    - bzip2
    - zlib
  run:
    - python
    - numpy >=1.22
    - scikit-image
    - vigra

test:
  imports:
    - nifty
    - nifty.graph
    - nifty.distributed  # [not win]
  source_files:
    - src/python/test/**/*.py
  commands:
    - python -m unittest discover -s src/python/test -v
  requires:
    - z5py

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  license_file: LICENSE
  summary: nifty

extra:
  recipe-maintainers:
    - constantinpape
    - DerThorsten
