{% set version = "1.2.1" %}

package:
  name: nifty
  version: {{ version }}

source:
  url: https://github.com/DerThorsten/nifty/archive/v{{ version }}.tar.gz
  sha256: a5fd611463336ba18be828da3154da8828b6486603e2a04f14a4520cb357661a
  patches:
    # https://github.com/DerThorsten/nifty/pull/146
    - 146_improve_find_python.patch

build:
  number: 5

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - xtensor >=0.24,<0.25
    - xtensor-python >=0.26,<0.27
    - libboost-devel
    - libvigra
    # Vigra Numpy is used at link time too
    - vigra
    - z5py >=2.0.11
    # build dependencies needed for z5
    - nlohmann_json
    - blosc
    - bzip2
    - zlib
  run:
    - python
    - numpy >=1.22
    - scikit-image
    - vigra

test:
  imports:
    - nifty
    - nifty.graph
    - nifty.distributed  # [not win]
  source_files:
    - src/python/test/**/*.py
  commands:
    - python -m unittest discover -s src/python/test -v
  requires:
    - z5py

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  license_file: LICENSE
  summary: nifty

extra:
  recipe-maintainers:
    - constantinpape
    - DerThorsten
