{% set version = "1.0.8" %}

package:
  name: nifty
  version: {{ version }}

source:
    url: https://github.com/DerThorsten/nifty/archive/v{{ version }}.tar.gz
    sha256: 4a70eb106a926271cf86cae3e568c71b26ca40ecdfbfc337110f485410aa2876

build:
  number: 5

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make
  host:
    - python
    - numpy
    - xtensor >=0.21,<0.22
    - xtensor-python >=0.24,<0.25
    - vigra
    - hdf5
    - z5py >=2.0.8
    # macos needs boost as rt dependency because of boost filesystem
    - boost-cpp  # [osx]
    # build dependencies needed for z5
    - nlohmann_json >=3.10,<3.10.3
    - blosc
    - bzip2
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - boost-cpp  # [osx]

test:
  imports:
    - nifty
    - nifty.graph
    - nifty.distributed  # [not win]
  source_files:
    - src/python/test/**/*.py
  commands:
    - python -m unittest discover -s src/python/test -v
  requires:
    - z5py

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  license_file: LICENSE
  summary: nifty

extra:
  recipe-maintainers:
    - constantinpape
    - DerThorsten
